# These are supported funding model platforms
THONG NGO
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [thongngo1, thongngo2]
patreon: # Replace with a single Patreon username: thongngo
open_collective: # Replace with a single Open Collective username: thongngo
ko_fi: # Replace with a single Ko-fi username: thongngo
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., techvietco.vn
liberapay: # Replace with a single Liberapay username: thongngo1
issuehunt: # Replace with a single IssueHunt username: thongngo2
otechie: # Replace with a single Otechie username: thongngo
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['techvietco.vn']
